In [1]:
import torch;
print(torch.__version__);

2.3.0+cu121


In [2]:
if torch.cuda.is_available():
    print('GPU is available!')
else:
    print('GPU not available')

GPU not available


In [3]:
### create tensors having empty, 0, 1 or random values
tensor = torch.zeros(4);
a = torch.empty(2, 5);
r = torch.rand(2, 3)
print(a);
print(a[0][1]);

print(a[:, 0:2]) # creates tensor with all rows and first 2 columns of `e`.
print(id(a)); # view memory address of a tensor

tensor([[4.2039e-45, 4.2039e-45, 5.6052e-45, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4854e-43, 4.2039e-45]])
tensor(4.2039e-45)
tensor([[4.2039e-45, 4.2039e-45],
        [0.0000e+00, 0.0000e+00]])
140307577247680


In [4]:
# ** create tensors with random numbers from a seed **
seed = torch.manual_seed(350);
random_seed = torch.rand(2, 3);

print(random_seed);

tensor([[0.6256, 0.4304, 0.3596],
        [0.5186, 0.0569, 0.6557]])


In [5]:
# ** create tensors that already have values/shape, are in a range, make a identity matrix, are linearly distributed
filled_tsr = torch.tensor([[2.7,3], [4.55,5]], dtype=torch.int32);
fixed_tsr = torch.full(size=[3, 4], fill_value=4);
ranged_tsr = torch.arange(2, 8, 3);
identity_matrix_tsr = torch.eye(4, dtype=torch.int32);
linear_tsr = torch.linspace(1, 10, 8, dtype=torch.float32);

print(filled_tsr);
print(fixed_tsr);
print(ranged_tsr);
print(identity_matrix_tsr);
print(linear_tsr);


tensor([[2, 3],
        [4, 5]], dtype=torch.int32)
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])
tensor([2, 5])
tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]], dtype=torch.int32)
tensor([ 1.0000,  2.2857,  3.5714,  4.8571,  6.1429,  7.4286,  8.7143, 10.0000])


$$linspace(a, b, s) = [\sum \limits _{n=0}^{s-1} (a+n*\frac{b-a}{s-1})]$$

#### Tensor Shapes

In [6]:
print(type(ranged_tsr));
print(fixed_tsr.shape); # python attribute
print(linear_tsr.dtype);

# convert to int32
converted = linear_tsr.to(torch.int64);
print(converted);

#copy shape
torch.rand_like(converted, dtype=torch.float32) # integer tensor cannot be input to rand_like without dtype



<class 'torch.Tensor'>
torch.Size([3, 4])
torch.float32
tensor([ 1,  2,  3,  4,  6,  7,  8, 10])


tensor([0.5143, 0.2342, 0.2308, 0.8509, 0.3374, 0.8921, 0.9959, 0.6675])

#### Copying Tensors

In [7]:
src = torch.tensor([
    [2, 3, 5],
    [40, 15, 12]
]);

dst = src; # reference remains same in this copy
print(id(src) == id(dst)); # returns boolean `True`

# copy with change in reference
dst = src.clone();
print(id(src) == id(dst)); # returns boolean `False`

True
False
