In [57]:
import torch;
print(torch.__version__);

2.3.0+cu121


#### Mathematical Operations

In [58]:
source = torch.tensor([
    [10, 24, 20],
    [5, 8, 12]
]);

# print(source.dtype);
# print(source + 2);

# in place addition
# print(source.add_(2));
# print(source)

# print(source - 2);
# print(source * 2);
# print((source / 2).to(torch.int64));

# integer division
print(source // 2);
# mod
print(source % 2);
# power
source ** 2

tensor([[ 5, 12, 10],
        [ 2,  4,  6]])
tensor([[0, 0, 0],
        [1, 0, 0]])


tensor([[100, 576, 400],
        [ 25,  64, 144]])

#### Element Wise Matrix Operations

In [59]:
a = torch.tensor([
    [4.5, 10.25, 15],
    [20, 8.5, 12]
]);
b = torch.tensor([
    [50, 20, 12],
    [7.5, 25, 8]
]);

# print(a.shape, b.shape); 2x3 matrix
# print((a + b).to(torch.int64));

# in place addition
# print(a.add_(b));
# print(a);

# print(a / b);
print(a * b);
print(a // b);
print(a % b);
print(a ** b);

c = torch.tensor([1, -2, 3, -4]);
d = torch.tensor([
    [1.5, -2.3, 2.5, 4.7],
    [4.6, 7.56, 8.2, -10.6]
]);
# print(torch.abs(c));
# print(torch.neg(c));
print(torch.round(d, decimals=1));
# print(torch.ceil(d));
# print(torch.floor(d));
print(torch.clamp(d, min=3, max=7));


tensor([[225.0000, 205.0000, 180.0000],
        [150.0000, 212.5000,  96.0000]])
tensor([[0., 0., 1.],
        [2., 0., 1.]])
tensor([[ 4.5000, 10.2500,  3.0000],
        [ 5.0000,  8.5000,  4.0000]])
tensor([[4.5775e+32, 1.6386e+20, 1.2975e+14],
        [5.7243e+09, 1.7198e+23, 4.2998e+08]])
tensor([[  1.5000,  -2.3000,   2.5000,   4.7000],
        [  4.6000,   7.6000,   8.2000, -10.6000]])
tensor([[3.0000, 3.0000, 3.0000, 4.7000],
        [4.6000, 7.0000, 7.0000, 3.0000]])


#### Reduction Operations

In [60]:
e = torch.tensor([
    [1, 14, 9],
    [4, 100, 20]
]);

# sum of tensor
# print(torch.sum(e));
# sum along columns only
# print(torch.sum(e, dim=0, keepdim=True));
# sum along rows only
# print(torch.sum(e, dim=1, keepdim=True));

# print(torch.mean(e, dtype=torch.float32, dim=0, keepdim=True));
# print(torch.median(e));
# print(torch.mode(e, dim=0, keepdim=True).values);
# Standard deviation
# print(torch.std(e.to(torch.float32)));
# Variance
# print(torch.var(e.to(torch.float32)));

# Determinant
print(torch.det(e[:, 0:2].to(torch.float32)));

# Inverse
print(torch.inverse(e[:, 0:2].to(torch.float32)));

# Logarithm
# print(torch.log(e)); # Natural log
# print(torch.log10(e)); # Log with base 10

# Exponential
# print(torch.exp(e)); # Exponential of Euler's number (e)
# print(torch.exp2(e));

# Square root
# print(torch.sqrt(e));

# Sigmoid
# print(torch.sigmoid(e));

# Softmax - Rescales elements along a dimension to make the sum as 1.
smax = torch.softmax(e, 0, dtype=torch.float32);
# print(torch.sum(smax, 0));
# print(smax);

# relu - sets all negative numbers to 0. 
rel = torch.tensor([
    [-1, 2, 5.5],
    [0.2, 0, -2.5]
]);
# print(torch.relu(rel));


tensor(44.0000)
tensor([[ 2.2727, -0.3182],
        [-0.0909,  0.0227]])


In [61]:
print(torch.max(e));
print(torch.min(e));
print(torch.argmax(e));
print(torch.argmin(e));
print(torch.prod(e));

tensor(100)
tensor(1)
tensor(4)
tensor(0)
tensor(1008000)


#### Matrix Operations

In [62]:
f = torch.tensor([
    [4.5, 10.25, 15],
    [20, 8.5, 12]
]);
g = torch.tensor([
    [50, 20],
    [12, 7.5],
    [25, 8]
]);

# Matrix multiplication
print(torch.matmul(f, g));
tensor1 = torch.tensor([4, 3]);
tensor2 = torch.tensor([
    [1, 3, 5, 7],
    [2, 4, 6, 8]
]);
# print(tensor1.shape);print(tensor2.shape);
# print(torch.matmul(tensor1, tensor2));

# Dot product
tsr1 = torch.tensor([2, 4, 6]);
tsr2 = torch.tensor([1, 3, 5]);
print(torch.dot(tsr1, tsr2));

# Transpose matrix
print(torch.transpose(f, 0, 1));

tensor([[ 723.0000,  286.8750],
        [1402.0000,  559.7500]])
tensor(44)
tensor([[ 4.5000, 20.0000],
        [10.2500,  8.5000],
        [15.0000, 12.0000]])


#### Comparison Operations

In [63]:
h = torch.tensor([
    [10, 55, 60],
    [25, 5, 4]
]);
i = torch.tensor([
    [23, 45, 50],
    [25, 7, 10]
]);

# print(h > i);
# print(h >= i);
# print(h < i);
print(h == i);
print(h != i);


tensor([[False, False, False],
        [ True, False, False]])
tensor([[ True,  True,  True],
        [False,  True,  True]])
